---
- name: Allows container communication to an other containers
  ansible.posix.firewalld:
    zone: public
    masquerade: enabled
    permanent: yes
    immediate: true
    state: enabled
    
- name: Allow port 2375 expose to outside network
  ansible.posix.firewalld:
    zone: public
    port: 2375/tcp
    permanent: yes
    immediate: true
    state: enabled