---
# tasks file for ansible-role-docker
- name: Configure Security-enhanced
  block: 
    - name: Set selinux permissive module on RedHat family
      ansible.posix.selinux:
        policy: targeted
        state: permissive
      when: ansible_facts['os_family'] == 'RedHat'
    
    - name: Add firewall-cmd docker communication on RedHat family
      include_tasks: common/el/firewall-cmd.yaml
      when: ansible_facts['os_family'] == 'RedHat'

- name: Install pre-requisites for docker
  block: 
    - name: Install dependencies for CentOS
      include_tasks: common/el/docker-centos-deps.yaml
      when: ansible_facts['distribution'] == 'CentOS'

    - name: Intall dependencies for Ubuntu
      include_tasks: common/debian/docker-ubuntu-deps.yaml
      when: ansible_facts['distribution'] == 'Ubuntu'
    
    - name: Intall docker-py
      include_tasks: common/pip-docker.yaml

- name: Install docker packages
  block: 
    - name: Install docker-ce for CentOS
      include_tasks: package/el/docker-centos.yaml
      when: ansible_facts['distribution'] == 'CentOS'
    
    - name: Install docker-ce for Ubuntu
      include_tasks: package/debian/docker-ubuntu.yaml
      when: ansible_facts['distribution'] == 'Ubuntu'

- name: Post-Install docker, executeable non-root
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Post-Install docker, config daemon.json
  include_tasks: config/docker-daemon-conf.yaml